
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - credential.github.com
  resources:
  - githubdeploykeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - credential.github.com
  resources:
  - githubdeploykeys/finalizers
  verbs:
  - update
- apiGroups:
  - credential.github.com
  resources:
  - githubdeploykeys/status
  verbs:
  - get
  - patch
  - update
